# This workflow will prepare the data, that will be used for the oscalcli tool, for deployment to node package manager (NPM)
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

#name: Oscalcli CI
name: Project1 CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # checkout the CLI tool
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: install xslt3
      run: npm install xslt3 -g
    - name: clone OSCAL repo and copy files to destinations
      run: |
        git clone https://github.com/usnistgov/OSCAL.git

        mkdir -p lib/converter/json lib/converter/xml
        mkdir -p lib/validator/json lib/validator/xml

        mv OSCAL/json/convert/*.xsl lib/converter/json
        mv OSCAL/xml/convert/*.xsl lib/converter/xml

        mv OSCAL/json/schema/*.json lib/validator/json
        mv OSCAL/xml/schema/*.xsd lib/validator/xml

    - name: clone METASCHEMA repo and copy files to destinations
      run: |
        git clone https://github.com/usnistgov/metaschema.git

        mkdir -p lib/validator/support/xml
        mv metaschema/support/xml/xml.xsd metaschema/support/xml/XMLSchema.xsd lib/validator/support/xml

        mkdir -p lib/stylesheet/sef lib/stylesheet/raw

        rm metaschema/toolchains/xslt-M4/nist-metaschema-MAKE-XML-METATRON.xsl

    - name: create .sef files and copy files to destinations
      run: |
        FILES=$(ls metaschema/toolchains/xslt-M4/nist-metaschema-MAKE-*.xsl)

        for FILE in $FILES
        do
          FILENAME=$(basename $FILE)
          NEWFILE="${FILENAME%.*}"
          xslt3 -t -xsl:${FILE} -export:${NEWFILE}.sef.json -nogo
          mv ${NEWFILE}.sef.json lib/stylesheet/sef
          mv $FILE lib/stylesheet/raw
        done
    - name: clean up
      run: |
        rm -rf OSCAL
        rm -rf metaschema
    # This will be changed to npm repository deployment
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP}} #Must be unique in Heroku
        heroku_email: ${{secrets.HEROKU_EMAIL}}
